// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'bulk_order_detail_t_item_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BulkOrderDetailTItemModel _$BulkOrderDetailTItemModelFromJson(
        Map<String, dynamic> json) =>
    BulkOrderDetailTItemModel(
      json['AEDAT'] as String?,
      json['AENAM'] as String?,
      json['AEWID'] as String?,
      json['AEZET'] as String?,
      json['BOX_UMREZ'] as int?,
      json['EAN11'] as String?,
      json['ERDAT'] as String?,
      json['ERNAM'] as String?,
      json['ERWID'] as String?,
      json['ERZET'] as String?,
      (json['KWMENG'] as num?)?.toDouble(),
      json['LOEVM'] as String?,
      json['LOEVM_OR'] as String?,
      json['MAKTX'] as String?,
      json['MANDT'] as String?,
      json['MATNR'] as String?,
      (json['MWSBP'] as num?)?.toDouble(),
      (json['NETPR'] as num?)?.toDouble(),
      (json['NETWR'] as num?)?.toDouble(),
      json['POSNR'] as String?,
      json['SET_UMREZ'] as int?,
      json['UMODE'] as String?,
      json['VBELN'] as String?,
      json['VDATU'] as String?,
      json['VRKME'] as String?,
      json['WAERK'] as String?,
      json['WERKS'] as String?,
      json['WERKS_NM'] as String?,
      (json['ZDIS_PRICE'] as num?)?.toDouble(),
      (json['ZDIS_RATE'] as num?)?.toDouble(),
      json['ZERR'] as String?,
      json['ZFREE'] as String?,
      json['ZFREE_CHK'] as String?,
      (json['ZFREE_QTY'] as num?)?.toDouble(),
      (json['ZFREE_QTY_IN'] as num?)?.toDouble(),
      (json['ZKWMENG'] as num?)?.toDouble(),
      json['ZMESSAGE'] as String?,
      (json['ZMIN_QTY'] as num?)?.toDouble(),
      json['ZMSG'] as String?,
      (json['ZNETPR'] as num?)?.toDouble(),
      json['ZREQNO'] as String?,
      json['ZREQPO'] as String?,
      json['ZSTATUS'] as String?,
      json['ZSTSTX'] as String?,
      json['isShowLoading'] as bool?,
      json['isFirstRun'] as bool?,
    );

Map<String, dynamic> _$BulkOrderDetailTItemModelToJson(
        BulkOrderDetailTItemModel instance) =>
    <String, dynamic>{
      'MANDT': instance.mandt,
      'ZREQNO': instance.zreqno,
      'ZREQPO': instance.zreqpo,
      'MATNR': instance.matnr,
      'WERKS': instance.werks,
      'KWMENG': instance.kwmeng,
      'ZNETPR': instance.znetpr,
      'NETPR': instance.netpr,
      'ZDIS_RATE': instance.zdisRate,
      'ZDIS_PRICE': instance.zdisPrice,
      'ZFREE_QTY': instance.zfreeQty,
      'ZFREE_QTY_IN': instance.zfreeQtyIn,
      'VRKME': instance.vrkme,
      'NETWR': instance.netwr,
      'MWSBP': instance.mwsbp,
      'WAERK': instance.waerk,
      'VBELN': instance.vbeln,
      'POSNR': instance.posnr,
      'ZMIN_QTY': instance.zminQty,
      'ZMESSAGE': instance.zmessage,
      'ZMSG': instance.zmsg,
      'ZSTSTX': instance.zststx,
      'LOEVM': instance.loevm,
      'LOEVM_OR': instance.loevmOr,
      'ZFREE': instance.zfree,
      'VDATU': instance.vkatu,
      'ERDAT': instance.erdat,
      'ERZET': instance.erzet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'AEZET': instance.aezet,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'MAKTX': instance.maktx,
      'WERKS_NM': instance.werksNm,
      'ZERR': instance.zerr,
      'ZSTATUS': instance.zstatus,
      'UMODE': instance.umode,
      'ZFREE_CHK': instance.zfreeChk,
      'EAN11': instance.ean11,
      'ZKWMENG': instance.zkwmeng,
      'SET_UMREZ': instance.setUmrez,
      'BOX_UMREZ': instance.boxUmrez,
      'isShowLoading': instance.isShowLoading,
      'isFirstRun': instance.isFirstRun,
    };
