// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'bulk_order_detail_t_header_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BulkOrderDetailTHeaderModel _$BulkOrderDetailTHeaderModelFromJson(
        Map<String, dynamic> json) =>
    BulkOrderDetailTHeaderModel(
      json['AEDAT'] as String?,
      json['AENAM'] as String?,
      json['AEWID'] as String?,
      json['AEZET'] as String?,
      json['AUART'] as String?,
      json['BSTKD'] as String?,
      json['BUKRS'] as String?,
      json['DDATE'] as String?,
      json['DPTCD'] as String?,
      json['EMPNO'] as String?,
      json['ERDAT'] as String?,
      json['ERNAM'] as String?,
      json['ERWID'] as String?,
      json['KUNNR'] as String?,
      json['KUNNR_NM'] as String?,
      json['KUNWE'] as String?,
      json['LOEVM'] as String?,
      json['LOEVM_OR'] as String?,
      json['MANDT'] as String?,
      (json['MWSBP_SUM'] as num?)?.toDouble(),
      (json['NETWR_SUM'] as num?)?.toDouble(),
      json['ORERR'] as String?,
      json['ORGHK'] as String?,
      json['PERNR'] as String?,
      json['PERNR_NM'] as String?,
      json['REQNO'] as String?,
      json['ERZET'] as String?,
      json['SANUM'] as String?,
      json['SANUMNM'] as String?,
      json['SLNUM'] as String?,
      json['SPART'] as String?,
      json['UMODE'] as String?,
      json['VBELN'] as String?,
      json['VDATU'] as String?,
      json['VKGRP'] as String?,
      json['VKGRP_NM'] as String?,
      json['VKORG'] as String?,
      json['VTWEG'] as String?,
      json['WAERK'] as String?,
      json['XCONF'] as String?,
      json['XCONF_NM'] as String?,
      json['ZDMSTATUS'] as String?,
      json['ZDMSTATUS_NM'] as String?,
      json['ZREQ_DATE'] as String?,
      json['ZREQNO'] as String?,
      json['ZSTATUS'] as String?,
      json['ZSTATUS_NM'] as String?,
      json['ZZKUNNR_END'] as String?,
      json['ZZKUNNR_END_NM'] as String?,
    );

Map<String, dynamic> _$BulkOrderDetailTHeaderModelToJson(
        BulkOrderDetailTHeaderModel instance) =>
    <String, dynamic>{
      'MANDT': instance.mandt,
      'ZREQNO': instance.zreqno,
      'ZREQ_DATE': instance.zreqDate,
      'VTWEG': instance.vtweg,
      'SPART': instance.spart,
      'VKGRP': instance.vkgrp,
      'PERNR': instance.pernr,
      'KUNNR': instance.kunnr,
      'KUNWE': instance.kunwe,
      'ZZKUNNR_END': instance.zzkunnrEnd,
      'BSTKD': instance.bstkd,
      'VBELN': instance.vbeln,
      'LOEVM': instance.loevm,
      'ORERR': instance.orerr,
      'LOEVM_OR': instance.loevmOr,
      'XCONF': instance.xconf,
      'VDATU': instance.vdatu,
      'REQNO': instance.reqno,
      'ZDMSTATUS': instance.zdmstatus,
      'BUKRS': instance.bukrs,
      'VKORG': instance.vkorg,
      'DPTCD': instance.dptcd,
      'ORGHK': instance.orghk,
      'SANUM': instance.sanum,
      'SLNUM': instance.slnum,
      'ERDAT': instance.erdat,
      'ERZET': instance.rezet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'AEZET': instance.aezet,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'SANUMNM': instance.sanumnm,
      'KUNNR_NM': instance.kunnrNm,
      'ZZKUNNR_END_NM': instance.zzkunnrEndNm,
      'EMPNO': instance.empno,
      'UMODE': instance.umode,
      'ZSTATUS': instance.zstatus,
      'ZSTATUS_NM': instance.zstatusNm,
      'PERNR_NM': instance.pernrNm,
      'VKGRP_NM': instance.vkgrpNm,
      'XCONF_NM': instance.xconfNm,
      'NETWR_SUM': instance.netwrSum,
      'MWSBP_SUM': instance.mwsbpSum,
      'WAERK': instance.waerk,
      'AUART': instance.auart,
      'DDATE': instance.ddate,
      'ZDMSTATUS_NM': instance.zdmstatusNm,
    };
