// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'et_customer_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EtCustomerModel _$EtCustomerModelFromJson(Map<String, dynamic> json) =>
    EtCustomerModel(
      json['ISVALID'] as String?,
      json['KUNNR'] as String?,
      json['NAME'] as String?,
      json['ORGHK'] as String?,
      json['ORGHK_NM'] as String?,
      json['PER_NAM'] as String?,
      json['PERNR'] as String?,
      json['POOLCK'] as String?,
      json['POST_CODE1'] as String?,
      json['SANUM'] as String?,
      json['SANUM_NM'] as String?,
      json['TELF1'] as String?,
      json['VKGRP'] as String?,
      json['YOYANG_NO'] as String?,
      json['ZADD_NAME1'] as String?,
      json['ZADD_NAME2'] as String?,
      json['ZADD_NAME3'] as String?,
      json['ZADD_NAME4'] as String?,
      json['ZBIZ'] as String?,
      json['ZBIZ_NM'] as String?,
      json['ZBNO'] as String?,
      json['ZBTNO'] as String?,
      json['ZCHIEF'] as String?,
      json['ZCLASS'] as String?,
      json['ZCLOSEYN'] as String?,
      json['ZDIRECTOR'] as String?,
      json['ZEMP_NO'] as String?,
      json['ZHKUNNR'] as String?,
      json['ZIMPORT'] as String?,
      json['ZINPUT_CLSS'] as String?,
      json['ZKIND'] as String?,
      json['ZKIND_NM'] as String?,
      json['ZLOEVM'] as String?,
      json['ZOPENDAT'] as String?,
      json['ZPARMA_NO'] as String?,
      json['ZPNO1'] as String?,
      json['ZREMARK'] as String?,
      json['ZSALES_AVG'] as String?,
      json['ZSALES_NO1'] as String?,
      json['ZSALES_NO2'] as String?,
      json['ZSKUNNR'] as String?,
      json['ZSTATUS'] as String?,
      json['ZSTATUS_NM'] as String?,
      json['ZTRD_AREA'] as String?,
      json['ZTREAT2'] as String?,
      json['ZTREAT2_NM'] as String?,
      json['ZTREAT3'] as String?,
      json['ZTREAT3_NM'] as String?,
      json['ZYAR_AMT'] as String?,
    );

Map<String, dynamic> _$EtCustomerModelToJson(EtCustomerModel instance) =>
    <String, dynamic>{
      'ZHKUNNR': instance.zhkunnr,
      'ZSKUNNR': instance.zskunnr,
      'NAME': instance.name,
      'ZSTATUS': instance.zstatus,
      'TELF1': instance.telf1,
      'POST_CODE1': instance.postCode1,
      'ZADD_NAME1': instance.zaddName1,
      'ZADD_NAME2': instance.zaddName2,
      'ZADD_NAME3': instance.zadoName3,
      'ZADD_NAME4': instance.zadoName4,
      'PERNR': instance.pernr,
      'VKGRP': instance.vkgrp,
      'ZLOEVM': instance.zloevm,
      'POOLCK': instance.poolck,
      'ZTREAT2': instance.ztreat2,
      'ZTREAT2_NM': instance.ztreat2Nm,
      'ZOPENDAT': instance.zopendat,
      'ZPNO1': instance.zpno1,
      'ZBNO': instance.zbno,
      'ZBTNO': instance.zbtno,
      'ZDIRECTOR': instance.zdirector,
      'ZCHIEF': instance.zchief,
      'ZEMP_NO': instance.zempNo,
      'ZSALES_NO1': instance.zsalesNo1,
      'ZTRD_AREA': instance.ztrdArea,
      'ZSALES_AVG': instance.zsalesAvg,
      'ZYAR_AMT': instance.zyarAmt,
      'ZSALES_NO2': instance.zsalesNo2,
      'ZPARMA_NO': instance.zparmaNo,
      'ZREMARK': instance.zremark,
      'ZIMPORT': instance.zimport,
      'ZSTATUS_NM': instance.zstatusNm,
      'SANUM': instance.sanum,
      'SANUM_NM': instance.sanumNm,
      'ORGHK': instance.orghk,
      'ORGHK_NM': instance.orghkNm,
      'ZKIND': instance.zkind,
      'ZKIND_NM': instance.zkindNm,
      'ZTREAT3': instance.ztreat3,
      'ZTREAT3_NM': instance.ztreat3Nm,
      'ZCLASS': instance.zclass,
      'ZBIZ': instance.zbiz,
      'ZBIZ_NM': instance.zbizNm,
      'KUNNR': instance.kunnr,
      'ZINPUT_CLSS': instance.zinputClss,
      'PER_NAM': instance.perNam,
      'ISVALID': instance.isvalid,
      'YOYANG_NO': instance.yoyangNo,
      'ZCLOSEYN': instance.zcloseyn,
    };
