// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'recent_order_head_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RecentOrderHeadModel _$RecentOrderHeadModelFromJson(
        Map<String, dynamic> json) =>
    RecentOrderHeadModel(
      aedat: json['AEDAT'] as String?,
      aenam: json['AENAM'] as String?,
      aewid: json['AEWID'] as String?,
      bstkd: json['BSTKD'] as String?,
      bukrs: json['BUKRS'] as String?,
      dptcd: json['DPTCD'] as String?,
      empno: json['EMPNO'] as String?,
      erdat: json['ERDAT'] as String?,
      ernam: json['ERNAM'] as String?,
      erwid: json['ERWID'] as String?,
      erzet: json['ERZET'] as String?,
      kunnr: json['KUNNR'] as String?,
      kunnrNm: json['KUNNR_NM'] as String?,
      kunwe: json['KUNWE'] as String?,
      kunweNm: json['KUNWE_NM'] as String?,
      loevm: json['LOEVM'] as String?,
      loevmOr: json['LOEVM_OR'] as String?,
      mwsbpSum: json['MWSBP_SUM'] as double?,
      netwrSum: json['NETWR_SUM'] as double?,
      orerr: json['ORERR'] as String?,
      orghk: json['ORGHK'] as String?,
      pernr: json['PERNR'] as String?,
      pernrNm: json['PERNR_NM'] as String?,
      sanum: json['SANUM'] as String?,
      sanumnm: json['SANUMNM'] as String?,
      slnum: json['SLNUM'] as String?,
      spart: json['SPART'] as String?,
      umode: json['UMODE'] as String?,
      vbeln: json['VBELN'] as String?,
      vkgrp: json['VKGRP'] as String?,
      vkgrpNm: json['VKGRP_NM'] as String?,
      vkorg: json['VKORG'] as String?,
      vtweg: json['VTWEG'] as String?,
      waerk: json['WAERK'] as String?,
      xconf: json['XCONF'] as String?,
      xconfNm: json['XCONF_NM'] as String?,
      zreqDate: json['ZREQ_DATE'] as String?,
      zreqNo: json['ZREQNO'] as String?,
      zstatus: json['ZSTATUS'] as String?,
      zzkunnrEnd: json['ZZKUNNR_END'] as String?,
      zzkunnrEndNm: json['ZZKUNNR_END_NM'] as String?,
    );

Map<String, dynamic> _$RecentOrderHeadModelToJson(
        RecentOrderHeadModel instance) =>
    <String, dynamic>{
      'ZREQNO': instance.zreqNo,
      'ZREQ_DATE': instance.zreqDate,
      'VTWEG': instance.vtweg,
      'SPART': instance.spart,
      'VKGRP': instance.vkgrp,
      'PERNR': instance.pernr,
      'KUNNR': instance.kunnr,
      'KUNWE': instance.kunwe,
      'ZZKUNNR_END': instance.zzkunnrEnd,
      'BSTKD': instance.bstkd,
      'VBELN': instance.vbeln,
      'LOEVM': instance.loevm,
      'ORERR': instance.orerr,
      'LOEVM_OR': instance.loevmOr,
      'XCONF': instance.xconf,
      'BUKRS': instance.bukrs,
      'VKORG': instance.vkorg,
      'DPTCD': instance.dptcd,
      'ORGHK': instance.orghk,
      'SANUM': instance.sanum,
      'SLNUM': instance.slnum,
      'ERDAT': instance.erdat,
      'ERZET': instance.erzet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'SANUMNM': instance.sanumnm,
      'KUNNR_NM': instance.kunnrNm,
      'KUNWE_NM': instance.kunweNm,
      'ZZKUNNR_END_NM': instance.zzkunnrEndNm,
      'EMPNO': instance.empno,
      'UMODE': instance.umode,
      'ZSTATUS': instance.zstatus,
      'PERNR_NM': instance.pernrNm,
      'VKGRP_NM': instance.vkgrpNm,
      'XCONF_NM': instance.xconfNm,
      'NETWR_SUM': instance.netwrSum,
      'MWSBP_SUM': instance.mwsbpSum,
      'WAERK': instance.waerk,
    };
