// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sales_activity_day_table_260.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SalesActivityDayTable260 _$SalesActivityDayTable260FromJson(
        Map<String, dynamic> json) =>
    SalesActivityDayTable260(
      mandt: json['MANDT'] as String?,
      actcat: json['ACTCAT'] as String?,
      actcat1: json['ACTCAT1'] as String?,
      actcat2: json['ACTCAT2'] as String?,
      actcat3: json['ACTCAT3'] as String?,
      actcat4: json['ACTCAT4'] as String?,
      adate: json['ADATE'] as String?,
      aedat: json['AEDAT'] as String?,
      aenam: json['AENAM'] as String?,
      aewid: json['AEWID'] as String?,
      aezet: json['AEZET'] as String?,
      atime: json['ATIME'] as String?,
      bzactno: json['BZACTNO'] as String?,
      callType: json['CALL_TYPE'] as String?,
      comnt: json['COMNT'] as String?,
      dist: (json['DIST'] as num?)?.toDouble(),
      erdat: json['ERDAT'] as String?,
      ernam: json['ERNAM'] as String?,
      erwid: json['ERWID'] as String?,
      erzet: json['ERZET'] as String?,
      meetRmk: json['MEET_RMK'] as String?,
      rslt: json['RSLT'] as String?,
      seqno: json['SEQNO'] as String?,
      stpno: json['STPNO'] as String?,
      umode: json['UMODE'] as String?,
      visitRmk: json['VISIT_RMK'] as String?,
      xmeet: json['XMEET'] as String?,
      xvisit: json['XVISIT'] as String?,
      zaddName1: json['ZADD_NAME1'] as String?,
      zaddName2: json['ZADD_NAME2'] as String?,
      zaddName3: json['ZADD_NAME3'] as String?,
      zaddName4: json['ZADD_NAME4'] as String?,
      zaddr: json['ZADDR'] as String?,
      zkmno: json['ZKMNO'] as String?,
      zkmnoNm: json['ZKMNO_NM'] as String?,
      zskunnr: json['ZSKUNNR'] as String?,
      zskunnrNm: json['ZSKUNNR_NM'] as String?,
      zstatus: json['ZSTATUS'] as String?,
      accompany: json['ACCOMPANY'] as String?,
      accpNm: json['ACCP_NM'] as String?,
      comntM: json['COMNT_M'] as String?,
      etime: json['ETIME'] as String?,
      isGps: json['IS_GPS'] as String?,
      xLatitude: (json['X_LATITUDE'] as num?)?.toDouble(),
      yLongitude: (json['Y_LONGITUDE'] as num?)?.toDouble(),
      sminute: json['SMINUTE'] as String?,
      zkmtrust: json['ZKMTRUST'] as String?,
    );

Map<String, dynamic> _$SalesActivityDayTable260ToJson(
        SalesActivityDayTable260 instance) =>
    <String, dynamic>{
      'MANDT': instance.mandt,
      'ADATE': instance.adate,
      'ZKMTRUST': instance.zkmtrust,
      'BZACTNO': instance.bzactno,
      'SEQNO': instance.seqno,
      'ATIME': instance.atime,
      'ETIME': instance.etime,
      'ZSKUNNR': instance.zskunnr,
      'ZKMNO': instance.zkmno,
      'STPNO': instance.stpno,
      'XVISIT': instance.xvisit,
      'SMINUTE': instance.sminute,
      'VISIT_RMK': instance.visitRmk,
      'XMEET': instance.xmeet,
      'MEET_RMK': instance.meetRmk,
      'ACTCAT1': instance.actcat1,
      'ACTCAT2': instance.actcat2,
      'ACTCAT3': instance.actcat3,
      'ACTCAT4': instance.actcat4,
      'ZADDR': instance.zaddr,
      'DIST': instance.dist,
      'RSLT': instance.rslt,
      'ERDAT': instance.erdat,
      'ERZET': instance.erzet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'AEZET': instance.aezet,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'X_LATITUDE': instance.xLatitude,
      'Y_LONGITUDE': instance.yLongitude,
      'ZSKUNNR_NM': instance.zskunnrNm,
      'ACCOMPANY': instance.accompany,
      'ZKMNO_NM': instance.zkmnoNm,
      'ZADD_NAME1': instance.zaddName1,
      'ZADD_NAME2': instance.zaddName2,
      'ZADD_NAME3': instance.zaddName3,
      'ZADD_NAME4': instance.zaddName4,
      'ACTCAT': instance.actcat,
      'COMNT': instance.comnt,
      'COMNT_M': instance.comntM,
      'IS_GPS': instance.isGps,
      'ACCP_NM': instance.accpNm,
      'ZSTATUS': instance.zstatus,
      'CALL_TYPE': instance.callType,
      'UMODE': instance.umode,
    };
