// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sales_activity_day_table_250.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

SalesActivityDayTable250 _$SalesActivityDayTable250FromJson(
        Map<String, dynamic> json) =>
    SalesActivityDayTable250(
      mandt: json['MANDT'] as String?,
      adate: json['ADATE'] as String?,
      addcat: json['ADDCAT'] as String?,
      aedat: json['AEDAT'] as String?,
      aenam: json['AENAM'] as String?,
      aewid: json['AEWID'] as String?,
      aezet: json['AEZET'] as String?,
      bukrs: json['BUKRS'] as String?,
      bzactno: json['BZACTNO'] as String?,
      dptcd: json['DPTCD'] as String?,
      erdat: json['ERDAT'] as String?,
      ernam: json['ERNAM'] as String?,
      erwid: json['ERWID'] as String?,
      erzet: json['ERZET'] as String?,
      faddcat: json['FADDCAT'] as String?,
      fzaddr: json['FZADDR'] as String?,
      orghk: json['ORGHK'] as String?,
      orghkNm: json['ORGHK_NM'] as String?,
      rtnDist: (json['RTN_DIST'] as num?)?.toDouble(),
      saddcat: json['SADDCAT'] as String?,
      sanum: json['SANUM'] as String?,
      sanumNm: json['SANUM_NM'] as String?,
      slnum: json['SLNUM'] as String?,
      stat: json['STAT'] as String?,
      szaddr: json['SZADDR'] as String?,
      totDist: (json['TOT_DIST'] as num?)?.toDouble(),
      umode: json['UMODE'] as String?,
      vkorg: json['VKORG'] as String?,
      zaddr: json['ZADDR'] as String?,
      zaddr1: json['ZADDR1'] as String?,
      accompany: json['ACCOMPANY'] as String?,
      ftime: json['FTIME'] as String?,
      fxLatitude: (json['FX_LATITUDE'] as num?)?.toDouble(),
      fylongitude: (json['FY_LONGITUDE'] as num?)?.toDouble(),
      scallType: json['SCALL_TYPE'] as String?,
      stime: json['STIME'] as String?,
      sxLatitude: (json['SX_LATITUDE'] as num?)?.toDouble(),
      syLongitude: (json['SY_LONGITUDE'] as num?)?.toDouble(),
      fcallType: json['FCALL_TYPE'] as String?,
    );

Map<String, dynamic> _$SalesActivityDayTable250ToJson(
        SalesActivityDayTable250 instance) =>
    <String, dynamic>{
      'ADATE': instance.adate,
      'BZACTNO': instance.bzactno,
      'STAT': instance.stat,
      'ADDCAT': instance.addcat,
      'ZADDR': instance.zaddr,
      'SADDCAT': instance.saddcat,
      'SZADDR': instance.szaddr,
      'FADDCAT': instance.faddcat,
      'SX_LATITUDE': instance.sxLatitude,
      'SY_LONGITUDE': instance.syLongitude,
      'STIME': instance.stime,
      'SCALL_TYPE': instance.scallType,
      'FCALL_TYPE': instance.fcallType,
      'FX_LATITUDE': instance.fxLatitude,
      'FY_LONGITUDE': instance.fylongitude,
      'FTIME': instance.ftime,
      'FZADDR': instance.fzaddr,
      'ACCOMPANY': instance.accompany,
      'RTN_DIST': instance.rtnDist,
      'TOT_DIST': instance.totDist,
      'BUKRS': instance.bukrs,
      'VKORG': instance.vkorg,
      'DPTCD': instance.dptcd,
      'ORGHK': instance.orghk,
      'SANUM': instance.sanum,
      'SLNUM': instance.slnum,
      'ERDAT': instance.erdat,
      'ERZET': instance.erzet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'MANDT': instance.mandt,
      'AEZET': instance.aezet,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'ORGHK_NM': instance.orghkNm,
      'SANUM_NM': instance.sanumNm,
      'ZADDR1': instance.zaddr1,
      'UMODE': instance.umode,
    };
