// GENERATED CODE - DO NOT MODIFY BY HAND

part of 't_alarm_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TAlarmModel _$TAlarmModelFromJson(Map<String, dynamic> json) => TAlarmModel(
      json['MANDT'] as String?,
      json['ALMNO'] as String?,
      json['SEQNO'] as String?,
      json['DOCTY'] as String?,
      json['DOCNO'] as String?,
      json['ALMCD'] as String?,
      json['RCWID'] as String?,
      json['WRWID'] as String?,
      json['KUNNR'] as String?,
      json['KEY01'] as String?,
      json['KEY02'] as String?,
      json['BUKRS'] as String?,
      json['VKORG'] as String?,
      json['DPTCD'] as String?,
      json['ORGHK'] as String?,
      json['SANUM'] as String?,
      json['SLNUM'] as String?,
      json['MESSAGE'] as String?,
      json['TTEXT'] as String?,
      json['RCVCK'] as String?,
      json['REDCK'] as String?,
      json['OPDCK'] as String?,
      json['ERDAT'] as String?,
      json['ERZET'] as String?,
      json['ERNAM'] as String?,
      json['ERWID'] as String?,
      json['AEDAT'] as String?,
      json['AEZET'] as String?,
      json['AENAM'] as String?,
      json['AEWID'] as String?,
      json['UMODE'] as String?,
      json['rStatus'] as String?,
      json['rChk'] as String?,
      json['rSeq'] as String?,
    );

Map<String, dynamic> _$TAlarmModelToJson(TAlarmModel instance) =>
    <String, dynamic>{
      'MANDT': instance.mandt,
      'ALMNO': instance.almon,
      'SEQNO': instance.seqno,
      'DOCTY': instance.docty,
      'DOCNO': instance.docno,
      'ALMCD': instance.almcd,
      'RCWID': instance.rcwid,
      'WRWID': instance.wrwid,
      'KUNNR': instance.kunnr,
      'KEY01': instance.key01,
      'KEY02': instance.key02,
      'BUKRS': instance.bukrs,
      'VKORG': instance.vkorg,
      'DPTCD': instance.dptcd,
      'ORGHK': instance.orghk,
      'SANUM': instance.sanum,
      'SLNUM': instance.slnum,
      'MESSAGE': instance.message,
      'TTEXT': instance.ttext,
      'RCVCK': instance.rcvck,
      'REDCK': instance.redck,
      'OPDCK': instance.opdck,
      'ERDAT': instance.erdat,
      'ERZET': instance.erzet,
      'ERNAM': instance.ernam,
      'ERWID': instance.erwid,
      'AEDAT': instance.aedat,
      'AEZET': instance.aezet,
      'AENAM': instance.aenam,
      'AEWID': instance.aewid,
      'UMODE': instance.umode,
      'rStatus': instance.rStatus,
      'rChk': instance.rChk,
      'rSeq': instance.rSeq,
    };
