// GENERATED CODE - DO NOT MODIFY BY HAND

part of 't_list_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TlistModel _$TlistModelFromJson(Map<String, dynamic> json) => TlistModel(
      json['ACCOMPANY'] as String?,
      json['PVISIT'] as String?,
      json['ACCP_NM'] as String?,
      json['ACT_DTL'] as String?,
      json['ACT_FLAG'] as String?,
      json['ACTCAT1'] as String?,
      json['ACTCAT1_NM'] as String?,
      json['ACTCAT2'] as String?,
      json['ADATE'] as String?,
      json['ATIME'] as String?,
      json['BZACTNO'] as String?,
      json['CFM_FLAG'] as String?,
      json['COMNT'] as String?,
      (json['DIST'] as num?)?.toDouble(),
      json['FADDCAT'] as String?,
      json['FADDCAT_NM'] as String?,
      json['MAKTX1'] as String?,
      json['MAKTX2'] as String?,
      json['NAME'] as String?,
      json['MAKTX3'] as String?,
      json['MATKL'] as String?,
      json['MATNR1'] as String?,
      json['MATNR2'] as String?,
      json['MATNR3'] as String?,
      json['MEET_RMK'] as String?,
      json['MVGR1'] as String?,
      json['ORGHK'] as String?,
      json['ORGHK_NM'] as String?,
      json['PDESC'] as String?,
      json['RSLT'] as String?,
      json['SADDCAT'] as String?,
      json['SADDCAT_NM'] as String?,
      json['SANUM'] as String?,
      json['SANUM_NM'] as String?,
      json['SEQNO'] as String?,
      json['STAT'] as String?,
      json['STPNO'] as String?,
      json['UMODE'] as String?,
      json['VISIT_RMK'] as String?,
      json['VKGRP'] as String?,
      json['XMEET'] as String?,
      json['XTARGET'] as String?,
      json['XVISIT'] as String?,
      json['ZADDR'] as String?,
      json['ZBIZ'] as String?,
      json['ZKMNO'] as String?,
      json['ZKMNO_NM'] as String?,
      json['ZSKUNNR'] as String?,
      json['ZSKUNNR_NM'] as String?,
      json['ZSTATUS'] as String?,
      json['ZTREAT3'] as String?,
      json['ZTREAT3_NM'] as String?,
    );

Map<String, dynamic> _$TlistModelToJson(TlistModel instance) =>
    <String, dynamic>{
      'BZACTNO': instance.bzactno,
      'NAME': instance.name,
      'SEQNO': instance.seqno,
      'STPNO': instance.stpno,
      'ADATE': instance.adate,
      'ATIME': instance.atime,
      'ZSTATUS': instance.zstatus,
      'ZSKUNNR': instance.zskunnr,
      'ZSKUNNR_NM': instance.zskunnrNm,
      'ZKMNO': instance.zkmno,
      'ZKMNO_NM': instance.zkmnoNm,
      'ZADDR': instance.zaddr,
      'DIST': instance.dist,
      'XVISIT': instance.xvisit,
      'VISIT_RMK': instance.visitRmk,
      'XMEET': instance.xmeet,
      'MEET_RMK': instance.meetRmk,
      'ACTCAT1': instance.actcat1,
      'ACTCAT1_NM': instance.actcat1Nm,
      'ACTCAT2': instance.actcat2,
      'SANUM': instance.sanum,
      'ORGHK': instance.orghk,
      'SANUM_NM': instance.sanumNm,
      'ORGHK_NM': instance.orghkNm,
      'STAT': instance.stat,
      'ACT_DTL': instance.actDtl,
      'RSLT': instance.rslt,
      'XTARGET': instance.xtarget,
      'COMNT': instance.comnt,
      'SADDCAT': instance.saddcat,
      'FADDCAT': instance.faddcat,
      'SADDCAT_NM': instance.saddcatNm,
      'FADDCAT_NM': instance.faddcatNm,
      'ACT_FLAG': instance.actFlag,
      'CFM_FLAG': instance.cfmFlag,
      'PDESC': instance.pdesc,
      'VKGRP': instance.vkgrp,
      'ACCOMPANY': instance.accompany,
      'ACCP_NM': instance.accpNm,
      'MAKTX1': instance.maktx1,
      'MAKTX2': instance.maktx2,
      'MAKTX3': instance.maktx3,
      'MATNR1': instance.matnr1,
      'MATNR2': instance.matnr2,
      'MATNR3': instance.matnr3,
      'ZTREAT3': instance.ztreat3,
      'ZTREAT3_NM': instance.ztreat3Nm,
      'ZBIZ': instance.zbiz,
      'MATKL': instance.matkl,
      'MVGR1': instance.mvgr1,
      'UMODE': instance.umode,
      'PVISIT': instance.pvisit
    };
