// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'et_kunnr_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EtKunnrModel _$EtKunnrModelFromJson(Map<String, dynamic> json) => EtKunnrModel(
      isvalid: json['ISVALID'] as String?,
      kunnr: json['KUNNR'] as String?,
      name: json['NAME'] as String?,
      orghk: json['ORGHK'] as String?,
      orghkNm: json['ORGHK_NM'] as String?,
      perNam: json['PER_NAM'] as String?,
      pernr: json['PERNR'] as String?,
      poolck: json['POOLCK'] as String?,
      postCode1: json['POST_CODE1'] as String?,
      sanum: json['SANUM'] as String?,
      sanumNm: json['SANUM_NM'] as String?,
      telf1: json['TELF1'] as String?,
      vkgrp: json['VKGRP'] as String?,
      yoyangNo: json['YOYANG_NO'] as String?,
      zaddName1: json['ZADD_NAME1'] as String?,
      zaddName2: json['ZADD_NAME2'] as String?,
      zadoName3: json['ZADD_NAME3'] as String?,
      zadoName4: json['ZADD_NAME4'] as String?,
      zbiz: json['ZBIZ'] as String?,
      zbizNm: json['ZBIZ_NM'] as String?,
      zbno: json['ZBNO'] as String?,
      zbtno: json['ZBTNO'] as String?,
      zchief: json['ZCHIEF'] as String?,
      zclass: json['ZCLASS'] as String?,
      zcloseyn: json['ZCLOSEYN'] as String?,
      zdirector: json['ZDIRECTOR'] as String?,
      zempNo: json['ZEMP_NO'] as String?,
      zhkunnr: json['ZHKUNNR'] as String?,
      zimport: json['ZIMPORT'] as String?,
      zinputClss: json['ZINPUT_CLSS'] as String?,
      zkind: json['ZKIND'] as String?,
      zkindNm: json['ZKIND_NM'] as String?,
      zloevm: json['ZLOEVM'] as String?,
      zopendat: json['ZOPENDAT'] as String?,
      zparmaNo: json['ZPARMA_NO'] as String?,
      zpno1: json['ZPNO1'] as String?,
      zremark: json['ZREMARK'] as String?,
      zsalesAvg: json['ZSALES_AVG'] as String?,
      zsalesNo1: json['ZSALES_NO1'] as String?,
      zsalesNo2: json['ZSALES_NO2'] as String?,
      zskunnr: json['ZSKUNNR'] as String?,
      zstatus: json['ZSTATUS'] as String?,
      zstatusNm: json['ZSTATUS_NM'] as String?,
      ztrdArea: json['ZTRD_AREA'] as String?,
      ztreat2: json['ZTREAT2'] as String?,
      ztreat2Nm: json['ZTREAT2_NM'] as String?,
      ztreat3: json['ZTREAT3'] as String?,
      ztreat3Nm: json['ZTREAT3_NM'] as String?,
      zyarAmt: json['ZYAR_AMT'] as String?,
    );

Map<String, dynamic> _$EtKunnrModelToJson(EtKunnrModel instance) =>
    <String, dynamic>{
      'ZHKUNNR': instance.zhkunnr,
      'ZSKUNNR': instance.zskunnr,
      'NAME': instance.name,
      'ZSTATUS': instance.zstatus,
      'TELF1': instance.telf1,
      'POST_CODE1': instance.postCode1,
      'ZADD_NAME1': instance.zaddName1,
      'ZADD_NAME2': instance.zaddName2,
      'ZADD_NAME3': instance.zadoName3,
      'ZADD_NAME4': instance.zadoName4,
      'PERNR': instance.pernr,
      'VKGRP': instance.vkgrp,
      'ZLOEVM': instance.zloevm,
      'POOLCK': instance.poolck,
      'ZTREAT2': instance.ztreat2,
      'ZTREAT2_NM': instance.ztreat2Nm,
      'ZOPENDAT': instance.zopendat,
      'ZPNO1': instance.zpno1,
      'ZBNO': instance.zbno,
      'ZBTNO': instance.zbtno,
      'ZDIRECTOR': instance.zdirector,
      'ZCHIEF': instance.zchief,
      'ZEMP_NO': instance.zempNo,
      'ZSALES_NO1': instance.zsalesNo1,
      'ZTRD_AREA': instance.ztrdArea,
      'ZSALES_AVG': instance.zsalesAvg,
      'ZYAR_AMT': instance.zyarAmt,
      'ZSALES_NO2': instance.zsalesNo2,
      'ZPARMA_NO': instance.zparmaNo,
      'ZREMARK': instance.zremark,
      'ZIMPORT': instance.zimport,
      'ZSTATUS_NM': instance.zstatusNm,
      'SANUM': instance.sanum,
      'SANUM_NM': instance.sanumNm,
      'ORGHK': instance.orghk,
      'ORGHK_NM': instance.orghkNm,
      'ZKIND': instance.zkind,
      'ZKIND_NM': instance.zkindNm,
      'ZTREAT3': instance.ztreat3,
      'ZTREAT3_NM': instance.ztreat3Nm,
      'ZCLASS': instance.zclass,
      'ZBIZ': instance.zbiz,
      'ZBIZ_NM': instance.zbizNm,
      'KUNNR': instance.kunnr,
      'ZINPUT_CLSS': instance.zinputClss,
      'PER_NAM': instance.perNam,
      'ISVALID': instance.isvalid,
      'YOYANG_NO': instance.yoyangNo,
      'ZCLOSEYN': instance.zcloseyn,
    };
