name: medsalesportal
description: mkolon3.0 medsalesportal.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15  # flutter 공식지원
  webview_flutter: ^3.0.4 # flutter 공식지원
  connectivity_plus: ^2.3.5 # flutterCommunity 공식지원
  device_info_plus: ^0.0.1 # flutterCommunity 공식지원
  package_info_plus: ^0.0.1 # flutterCommunity 공식지원
  json_serializable: ^6.2.0 # google 공식지원
  json_annotation: ^4.5.0 # google 공식지원
  tuple: ^2.0.0  # google 공식지원
  path_provider: ^2.0.11 # flutter 공식지원
  url_launcher: ^6.1.4 # flutter 공식지원
  flutter_launcher_icons: ^0.9.3 # flutter 공식지원 
  dio: ^4.0.6 # flutter 공식지원
  provider: ^6.0.3 # dart 공식지원
  hive: ^2.2.3 # hive DB 공식지원
  hive_generator: ^1.1.3  # hive DB 공식지원
  permission_handler: ^10.0.0 # 유지보수 양호 
  easy_localization: ^3.0.1 # 유지보수 양호
  shimmer: ^2.0.0 # 유지보수 보통
  flutter_windowmanager: ^0.2.0 ### 유지보수 보통 ###
  flutter_screenutil: ^5.5.3+2 # 유지보수 양호
  flutter_svg: ^1.1.1 # 유지보수 양호 
  fluttertoast: ^8.0.9 # 유지보수 양호
  open_file: ^2.1.1 #### 폐기의심,현재 까지 사용가능.####  .apk 파일 open 용


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
flutter:
  uses-material-design: true

